"""EarthForge ``completions`` command — shell completion script generation.

Generates shell completion scripts for bash, zsh, and fish. The output is
printed to stdout so it can be redirected to the appropriate location:

    earthforge completions bash >> ~/.bashrc
    earthforge completions zsh  >> ~/.zshrc
    earthforge completions fish > ~/.config/fish/completions/earthforge.fish

Typer also installs completions automatically via the hidden flags
``--install-completion`` and ``--show-completion`` that it adds to the root
app. This module provides an explicit, documentable command as an alternative.
"""

from __future__ import annotations

import subprocess
import sys

import typer

_SUPPORTED_SHELLS = ("bash", "zsh", "fish")

_INSTRUCTIONS: dict[str, str] = {
    "bash": "# Add to ~/.bashrc:\n# source <(earthforge completions bash)",
    "zsh": "# Add to ~/.zshrc:\n# source <(earthforge completions zsh)",
    "fish": "# Save to ~/.config/fish/completions/earthforge.fish",
}


def completions(
    shell: str = typer.Argument(
        help=f"Shell to generate completions for: {', '.join(_SUPPORTED_SHELLS)}.",
    ),
) -> None:
    """Print a shell completion script to stdout.

    Redirect the output to your shell's configuration to enable tab completion:

        earthforge completions bash >> ~/.bashrc

        earthforge completions zsh >> ~/.zshrc

        earthforge completions fish > ~/.config/fish/completions/earthforge.fish
    """
    if shell not in _SUPPORTED_SHELLS:
        typer.echo(
            f"Error: unsupported shell '{shell}'. "
            f"Supported: {', '.join(_SUPPORTED_SHELLS)}",
            err=True,
        )
        raise typer.Exit(code=1)

    # Typer/Click exposes shell completions via the _COMPLETE env var mechanism.
    # We invoke the CLI subprocess with the appropriate env variable to capture
    # the completion script rather than re-implementing the generation logic.
    import os

    env_key = f"_{_app_name().upper().replace('-', '_')}_COMPLETE"
    env_val = f"{shell}_source"

    try:
        env = os.environ.copy()
        env[env_key] = env_val
        result = subprocess.run(
            [sys.executable, "-m", "earthforge"],
            env=env,
            capture_output=True,
            text=True,
            timeout=10,
        )
        script = result.stdout or result.stderr
    except (subprocess.TimeoutExpired, OSError):
        # Fallback: emit the instructions comment and let the user use
        # --show-completion instead
        script = ""

    if script.strip():
        typer.echo(f"# Generated by earthforge completions {shell}")
        typer.echo(f"{_INSTRUCTIONS[shell]}\n")
        typer.echo(script, nl=False)
    else:
        # Typer's built-in mechanism is more reliable — guide the user
        typer.echo(f"{_INSTRUCTIONS[shell]}\n")
        typer.echo(
            f"# Run the following to install completions directly:\n"
            f"earthforge --install-completion {shell}"
        )


def _app_name() -> str:
    """Return the CLI entry-point name for the completion env variable."""
    return "earthforge"
